### PR TITLE
read_array calls were failing

### PR DESCRIPTION
**Pull request by bill-mccormick-dg**
due to struct.pack exception 'cannot convert argument to integer'.

### CODE REVIEW

**Comment by ruscito** [comment]
what kind of exception are you getting?

**Comment by wpmccormick** [comment]
Hey, sorry took so long to get back to you on this. I had to move on to another project and somehow I missed your comment. I made need to revise my notification settings.

Beyond **struct.pack exception 'cannot convert argument to integer'.**, what else are you looking for? Are you not able to reproduce this?

**Comment by ruscito** [comment]
I guess we both are busy :) I'm not able to reproduce the error. Can you give me more details

Thanks

**Comment by wpmccormick** [comment]
I'm not really using pycomm any longer.

**Comment by ruscito** [comment]
I will close this since I can really reproduce the error

**Pull request closed without merging**
