### PR TITLE
adds u800 driver to read/write from Micro800 line of PLCs

### PR DESCRIPTION
**Pull request by patrickjmcd**
Also adds Micro800 example code

Tested on Micro820 PLC

### CODE REVIEW

**Comment by patrickjmcd** [comment]
Note that the class functions for forward_open and forward_close in the Base class are overwritten by the modified forward_open and forward_close functions in the Driver class for u800. This is really the only change I had to make.

**Comment by ruscito** [comment]
Hello patrickjmcd, 
first of all thanks for helping with the lib. I did some more in deep research about the Direct Connection, and I find out that this type of connection can be useful in other situations so I decided to merge your suggestions in the base class. Instead of having just a driver for the u800 you can use the regular driver (clx) and at run time pass a "True" parameter to the open method ( in your case it will be "c.open('10.20.158.3', True)" ).

I have changed the open method adding a defaulted parameter (direct_connection = False) this will guaranty back compatibility with previous users and at the same time give an opportunity to use "Direct Connections" when needed. 
I was able to test the  lib with Contrologix PLC but I don't have u800 series, so could you try and let me know if it works?



Thanks a lot
Agostino

**Comment by patrickjmcd** [comment]
Awesome. That sounds great to me. I'll test it tomorrow and report back.

**Comment by patrickjmcd** [comment]
I can confirm that the changes work on the micro800 for the direct connection. Since you've already made the changes, should I just close this PR?

**Comment by ruscito** [comment]
Yes please and if you don't mind I would like put a link to your url for
the credits :)
Again thanks for the help

Ago

**Pull request closed without merging**
